### PR TITLE
Add show_diff parameter to postfix::hash and postfix::map

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by raphink** [comment]
I suspect the goal of this feature is similar to that of #243, right?

**Comment by treydock** [comment]
I haven't used `Sensitive` yet but if that will suppress the diff content with `puppet.conf` has `show_diff = true` then #243 is a better approach.

**Comment by raphink** [comment]
`Sensitive` hides the content marked as sensitive from the outputs and reports.

**Comment by raphink** [comment]
I'll close this as I believe #243 fixes it.

**Pull request closed without merging**
