### PR TITLE
Data types

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by ubellavance** [comment]
Is this going to break puppet3 compatibility?

**Comment by raphink** [comment]
Yes, it definitely will.

**Comment by ubellavance** [comment]
Ok, would it be possible to create a branch that is puppet-3 compatible, like voxpupuli does, so that it's possible to make PRs on puppet3-compatible code? I know puppet 3 is EOL.

**Comment by raphink** [comment]
I would rather not. Puppet 4 has been out for 2 years now, it's a lot of work to maintain all our modules, and this is preventing from upgrading stdlib since validate functions are now deprecated.

**Pull request merged**
