### PR TITLE
Ruby231

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
These errors seem unrelated to my changes.

**Comment by ghoneycutt** [comment]
@camptocamp @ckaenzig Could you have a look please?

**Comment by ckaenzig** [comment]
The errors I see look like what I fixed in #154 (merged a couple of hours ago). Could you please rebase this PR on master?

**Comment by ghoneycutt** [comment]
Thanks @ckaenzig

**Comment by ghoneycutt** [comment]
This is passing the tests now. Could you please merge.

**Comment by ghoneycutt** [comment]
Hi @ckaenzig could you please merge

**Comment by ghoneycutt** [comment]
Hello @ckaenzig @camptocamp I have rebased. Are we good to merge?

**Comment by ghoneycutt** [comment]
@raphink could you please have a look

**Comment by ghoneycutt** [comment]
Thank you very much!

**Comment by mcanevet** [comment]
@raphink the `.travis.yaml` file is managed by modulesync (https://github.com/camptocamp/modulesync_configs/blob/master/moduleroot/.travis.yml) and thus this change will be reverted next time we'll sync this module... We should patch our modulesync_configs instead

**Comment by raphink** [comment]
Ack

**Pull request merged**
