### PR TITLE
Add possibility to specify a template for master.cf

### PR DESCRIPTION
**Pull request by jordiclariana**

### CODE REVIEW

**Comment by mcanevet** [comment]
@jordiclariana I'd prefer a more generic `mastercf_content` parameter and do the content generation in the caller class so that we can use any method to populate the content of the mastercf file (template(), file()...)

**Comment by jordiclariana** [comment]
I understand your point, but it conflicts with hiera and the "Automatic Parameter Lookup". It's not possible to call the function "template" inside hiera. I think that the way things are going on with puppet lately, trying to adapt modules to hiera is a good thing. What do you think?

**Comment by mcanevet** [comment]
@jordiclariana I think you should use hiera in your profiles layer so we keep the component as simple as possible:
```puppet
class profiles::postfix(
  mastercf_template,
) {
  class { '::postfix':
    mastercf_content => template($mastercf_template),
  }
}
```

**Comment by raphink** [comment]
@jordiclariana did @mcanevet's suggestion fix your issue?

**Comment by lingfish** [comment]
Why not just go the right way and use the postfix_master augeas lens?!?

**Comment by raphink** [comment]
@lingfish I'd welcome a PR for that

**Comment by c33s** [comment]
after playing around with my fork and epp templates i have to say the template function should reside inside this module because a normal/big template needs to many variables from this module.

conclusio for me is to simply support all three variants:

- sourced file
- content
- template name

see https://github.com/camptocamp/puppet-postfix/pull/217

**Pull request closed without merging**
