### PR TITLE
Make transport pattern accept regexp

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by raphink** [comment]
If you're using a Puppetfile, just make the module point to my repository with the proper git reference (the commit). If you want to test locally, you can just copy the lens file (`postfix_transport.aug`).

**Comment by OlivierLM** [comment]
Modified the lens file according to your patch.  What then plz?

**Comment by raphink** [comment]
Then you can try the code you provided in #92 and check if it applies properly

**Comment by OlivierLM** [comment]
Tested with 'augtool -i' then errors : fixed!

**Comment by raphink** [comment]
So that's good for you?

**Comment by OlivierLM** [comment]
Absolutely!

**Comment by OlivierLM** [comment]
Thinking about something…
Did you modify mta.pp ?
```
diff --git a/manifests/mta.pp b/manifests/mta.pp
index 0d742df390956593b301bc4d867d153f2c7923e6..ab1bcf97b41277dd002a2734a3db64887a55e646 100644
--- a/manifests/mta.pp
+++ b/manifests/mta.pp
@@ -47,8 +47,8 @@ class postfix::mta (
 
   postfix::config {
     'mynetworks':          value => $mynetworks;
-    'virtual_alias_maps':  value => 'hash:/etc/postfix/virtual';
-    'transport_maps':      value => 'hash:/etc/postfix/transport';
+    'virtual_alias_maps':  value => 'pcre:/etc/postfix/virtual';
+    'transport_maps':      value => 'pcre:/etc/postfix/transport';
   }
 
   postfix::hash { '/etc/postfix/virtual':

```

**Comment by raphink** [comment]
Not in this PR, no.

**Pull request merged**
