### PR TITLE
Make chroot parameter default to 'n'

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by lelutin** [comment]
Hi there, I've pushed 98fb0ce on top of this work on my fork of the module. It makes the $chroot parameter default to false and adds a deprecation warning if undef is used explicitely.

**Comment by raphink** [comment]
@lelutin 	there never was a release of this module with the `$chroot` parameter, it was only in git. So as far as I'm concerned the API is not fixed and there is no need for a deprecation warning.

**Comment by lelutin** [comment]
@raphink oh! right then my point about deprecation warning is moot. it would be nice then to make the parameter default to false and remove the undef value entirely, no?

**Comment by raphink** [comment]
Alright, let's merge this then.

**Pull request merged**
