### PR TITLE
PR Fixes issue #69 ldap-alias maps

### PR DESCRIPTION
**Pull request by phathocker**

### CODE REVIEW

**Comment by phathocker** [comment]
This is an update of PR #71

**Comment by mcanevet** [comment]
Why do you remove the quotes?

**Comment by raphink** [comment]
@mcanevet the answer is in https://github.com/camptocamp/puppet-postfix/issues/69

I wonder why we have this.

**Comment by raphink** [comment]
Apparently, I added this in 3f7ca33b

**Comment by mcanevet** [comment]
@raphink so do we merge this?

**Comment by raphink** [comment]
I guess this is OK. Do we have machines using this code @mcanevet?

**Comment by mcanevet** [comment]
@raphink we don't use this feature, that's probably why we didn't hit the bug.

**Pull request merged**
