### PR TITLE
support fedora versions 28 and later

### PR DESCRIPTION
**Pull request by qs5779**
I updated the spec tests, and have these changes active on a live Fedora 30 Server system.

### CODE REVIEW

**Comment by raphink** [comment]
Sorry for not addressing this earlier. Would you mind rebasing this PR?

**Comment by qs5779** [comment]
I tried to quickly deal with it when I first received you message, but "Fedora" being a RedHat family member with many more versions than rhel, coupled with fact I am now working on Archlinux support too, I believe a much better approach would be to leverage hieradata combined with the service_provider fact. That should make the logic much simpler.

If you disagree, please advise, and will accept your direction.

**Comment by qs5779** [comment]
I decided to rebase my changes. All spec tests passed after rebasing.

**Comment by raphink** [comment]
It's true that hiera data would probably simply this logic. I'd welcome a patch in this direction if you want to take it.

**Comment by qs5779** [comment]
I am closing this PR as I have finally had time to simplify the logic by leveraging hieradata. I will submit the new PR momentarily.

**Pull request closed without merging**
