### PR TITLE
Add chroot parameter

### PR DESCRIPTION
**Pull request by amateo**
To be able to configure master.cf with chroot.
This modification configures chroot field in the master.cf according to it.

### CODE REVIEW

**Comment by amateo** [comment]
This PR is failing with CI checks not directly related with it (it had problems building the ubuntu 16.04 docker container for the test).
Is there any problem with this?

**Comment by amateo** [comment]
Are planning to accept this PR? I had two problems with CI:

- I don't know why it is failing for ubuntu 16.04. It looks like a problem not directly related with the module. I have also run tests locally in my computer and it worked without any problem.The output error is:
```
An error occurred while loading ./spec/acceptance/postfix_spec.rb.
Failure/Error: require 'beaker-rspec'
Docker::Error::UnexpectedResponseError:
```
- It was failing on CentOS too. The problem when I run tests on my computer is that CentOS docker container does not have a ```127.0.0.1``` ip address which is the one used by default on _master.cf_. Forcing postfix to use all interfaces fixed the problem.

**Comment by raphink** [comment]
I restarted the Ubuntu 16.04 build to try and see what's wrong. Could you rebase this PR please?

**Comment by amateo** [comment]
I have rebased this PR, but it still failing in Ubuntu 16.04 CI tests.

**Comment by raphink** [comment]
OK. I will look into the 16.04 failure. Can you fix the other errors (linting)?

**Comment by raphink** [comment]
LGTM, although I'm not sure why you're replacing `$::fqdn` everywhere.

**Comment by amateo** [comment]
It fails in my puppet-lint configuration because $::fqdn is a legacy fact. Although I didn't write those lines, I didn't know if you want me to fix them.
I could revert if you want.

**Comment by raphink** [comment]
OK then, let's follow puppet-lint's advice.

**Comment by raphink** [comment]
That said, unit tests are still failing. Can you have a look at them?

**Comment by amateo** [comment]
I have to revert the changes for `$::fqdn`.

**Comment by amateo** [comment]
And the problem with Ubuntu 16.04 is not of my commits (I think). The error is:
```
An error occurred while loading ./spec/acceptance/postfix_spec.rb.
Failure/Error: require 'beaker-rspec'
Docker::Error::UnexpectedResponseError:
```
before launching any puppet test.
And when I test it locally it works without any problem.

**Comment by raphink** [comment]
Sorry for the delay. The Ubuntu 16.04 issue is clearly not this PR. However, there's still unit tests that are not passing, and this PR changes default behavior in Debian as far as I can tell.

**Comment by amateo** [comment]
Sorry for the delay. I can't see what errors do you want me to fix.
This PR doesn't change default behavior, it adds a parameter to configure postfix in a chroot environment, but if you don't use this parameter, the configuration is the same than your master branch.
The errors I can see in `PUPPET_GEM_VERSION="~> 4.0"` ([Job #428.1](https://travis-ci.org/camptocamp/puppet-postfix/jobs/249536230)) are all related to code I haven't written. Errors 8 to 26 are related with the content of the file _/etc/mailname_ which is created from _manifest/files.pp_ with a code wrote by Raphaël Pinson in 2013. I guess the problem is related with the hostname of the docker container running the test. Errors 1 to 7 I think they are also because of the hostname of the docker container, because default value is taken from `$::fqdn`.
It is happening the same with errors in `PUPPET_GEM_VERSION="~> 4"` ([Job #428.2](https://travis-ci.org/camptocamp/puppet-postfix/jobs/249536231))

**Pull request merged**
