### PR TITLE
Add a map define to create postfix maps

### PR DESCRIPTION
**Pull request by amateo**
It is similar to existing hash define, but this define can create maps
of any type, not just hash.

### CODE REVIEW

**Comment by raphink** [comment]
Couldn't this be done by patching `postfix::hash`? If not, could `postfix::hash` use this?

**Comment by amateo** [comment]
I think is better postfix::hash using postfix::map insteado of patching postfix::hash because naming postfix::hash to maps not using hashes could be confusing.

**Comment by raphink** [comment]
OK then. Could you provide that refactoring along with this PR then, to avoid duplicated code?

**Comment by raphink** [comment]
@amateo the PR makes the unit tests fail. Could you have a look at them please?

**Comment by amateo** [comment]
I don't know why it failed. I have run it in my system and it hasn't failed. Is there any way to re-run it?

**Comment by amateo** [comment]
I have fixed all acceptance test. Could you check it to merge it?

**Comment by spielkind** [comment]
If I use postfix::hash this is broken because I have to define an absolute path, which is used as name for postfix::map - which ends in a double definition of the the path.

```
  postfix::hash { '/etc/postfix/relay_passwd':
    ensure  => 'present',
    content => 'host.example.com user:password',
  }
```

> Error: Could not set 'present' on ensure: No such file or directory - /etc/postfix/etc/posfix/relay_passwd20161104-29513-11m325v.lock at 72:/etc/puppet/modules/postfix/manifests/map.pp
> Error: Could not set 'present' on ensure: No such file or directory - /etc/postfix/etc/posfix/relay_passwd20161104-29513-11m325v.lock at 72:/etc/puppet/modules/postfix/manifests/map.pp
> Wrapped exception:
> No such file or directory - /etc/postfix/etc/posfix/relay_passwd20161104-29513-11m325v.lock
> Error: /Stage[main]/Main/Node[default]/Postfix::Hash[/etc/posfix/relay_passwd]/Postfix::Map[/etc/posfix/relay_passwd]/File[postfix map /etc/posfix/relay_passwd]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory - /etc/postfix/etc/posfix/relay_passwd20161104-29513-11m325v.lock at 72:/etc/puppet/modules/postfix/manifests/map.pp
> Notice: /Stage[main]/Main/Node[default]/Postfix::Hash[/etc/posfix/relay_passwd]/Postfix::Map[/etc/posfix/relay_passwd]/Exec[generate /etc/posfix/relay_passwd.db]: Dependency File[postfix map /etc/posfix/relay_passwd] has failures: true
> Warning: /Stage[main]/Main/Node[default]/Postfix::Hash[/etc/posfix/relay_passwd]/Postfix::Map[/etc/posfix/relay_passwd]/Exec[generate /etc/posfix/relay_passwd.db]: Skipping because of failed dependencies
> Notice: /Stage[main]/Main/Node[default]/Postfix::Hash[/etc/posfix/relay_passwd]/Postfix::Map[/etc/posfix/relay_passwd]/File[postfix map /etc/posfix/relay_passwd.db]: Dependency File[postfix map /etc/posfix/relay_passwd] has failures: true
> Warning: /Stage[main]/Main/Node[default]/Postfix::Hash[/etc/posfix/relay_passwd]/Postfix::Map[/etc/posfix/relay_passwd]/File[postfix map /etc/posfix/relay_passwd.db]: Skipping because of failed dependencies
> 

```
  postfix::hash { 'relay_passwd':
    ensure  => 'present',
    content => 'host.example.com user:password',
  }
```

> 
Error: "relay_passwd" is not an absolute path

When I use postfix::map without absoulte path its broken because Exec has not the full path to the hash.

```
  postfix::map { 'relay_passwd':
    ensure  => 'present',
    content => 'host.example.com user:password',
  }
```

> Notice: /Stage[main]/Main/Node[default]/Postfix::Map[relay_passwd]/File[postfix map relay_passwd]/ensure: created
> Notice: /Stage[main]/Main/Node[default]/Postfix::Map[relay_passwd]/Exec[generate relay_passwd.db]/returns: postmap: fatal: open relay_passwd: No such file or directory
> Error: /Stage[main]/Main/Node[default]/Postfix::Map[relay_passwd]/Exec[generate relay_passwd.db]: Failed to call refresh: postmap relay_passwd returned 1 instead of one of [0]
> Error: /Stage[main]/Main/Node[default]/Postfix::Map[relay_passwd]/Exec[generate relay_passwd.db]: postmap relay_passwd returned 1 instead of one of [0]
> Notice: /Stage[main]/Main/Node[default]/Postfix::Map[relay_passwd]/File[postfix map relay_passwd.db]/ensure: created


I'm not sure how this supposed to work.

**Comment by amateo** [comment]
There are PRs (#149 or #153, for example) to fix this issue. They are pending for merge.

**Pull request merged**
