### PR TITLE
Add mailalias resource wrapper

### PR DESCRIPTION
**Pull request by micah**

### CODE REVIEW

**Comment by intrigeri** [comment]
I'm in the process of switching from https://gitlab.com/shared-puppet-modules-group/postfix to this module and lots of my codebase relies on `postfix::mailalias`, so I'll refresh this PR and make its doc fit better with the style of the module.

**Comment by intrigeri** [comment]
> OK. @micah 	do you think you could rebase this?

I'm on it :)

**Comment by intrigeri** [comment]
Done at https://github.com/intrigeri/puppet-postfix/tree/add_mailalias_wrapper. Should I create a new PR that will supersede this one, or is there a way to edit this PR so it's about this new branch?

**Comment by raphink** [comment]
@intrigeri 	I can change the destination branch but not the source, so you need to open a new PR.

**Comment by intrigeri** [comment]
I think this can now be closed.

**Comment by raphink** [comment]
Fixed in #233

**Pull request closed without merging**
