### PR TITLE
Fix issue with multiple mynetworks.

### PR DESCRIPTION
**Pull request by erinn**
This fixes issue #44 for you.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
+1 for that.

Just two things:
* Could you also set the default value to a more proper setting?
  Debian's default is: `127.0.0.0/8, [::ffff:127.0.0.0]/104, [::1]/128`
* squash and rebase your commits against the current master? (It's a bit cleaner)

**Comment by erinn** [comment]
The defaults for the test? They were just designed to test the syntax as much as possible, one lack a comma, one with a comma, etc.

**Comment by lazyfrosch** [comment]
@erinn the defaults for the module itself, we should support the IPv6 world wherever possible :)

**Comment by raphink** [comment]
Fixed by PR #80

**Pull request closed without merging**
