### PR TITLE
Add master_entries parameter to postfix

### PR DESCRIPTION
**Pull request by amateo**
It is an optional array of strings containing addtional entries for the
master.cf file

### CODE REVIEW

**Comment by raphink** [comment]
That looks good. Could you rebase this PR please?

**Comment by amateo** [comment]
Sorry for the delay. I have just rebased it.

**Comment by raphink** [comment]
@amateo Thanks. Actually, I've just fixed the Puppet 5 tests, so could you rebase once more please?

**Comment by amateo** [comment]
Rebased.

**Pull request merged**
