### PR TITLE
Add conffile define

### PR DESCRIPTION
**Pull request by amateo**
With it you can create postfix config files. It is a file, but it also reload postfix.

### CODE REVIEW

**Comment by raphink** [comment]
Could you add tests/doc please?

**Comment by raphink** [comment]
Thank you. I see failures related to this addition in the Travis CI runs (granted, there are other failures, too).

**Comment by amateo** [comment]
I think that CI checks failed because of errors not directly with these commits. For example, in job 346.9 that made the test on ubuntu 12.04 fails start at line 773 and it is because ```puppet``` command can't be found in the path. This is the same error starting at line 794.

**Comment by raphink** [comment]
E.g. in https://travis-ci.org/camptocamp/puppet-postfix/jobs/144119298, all the errors are linked to `conffile`.

**Comment by raphink** [comment]
That is much nicer already :smile:

**Pull request merged**
