### PR TITLE
Moved Exec['newaliases'] to services so it could be run after service restart

### PR DESCRIPTION
**Pull request by cdenneen**
This should fix the newalias issues found in the following tickets: #192 #136

### CODE REVIEW

**Comment by cdenneen** [comment]
Can someone look at travis... because it's completing successful but with exit code of 1

```
Finished in 44.2 seconds (files took 22.29 seconds to load)
708 examples, 0 failures, 14 pending
```

**Comment by cdenneen** [comment]
@raphink @mcanevet can someone look at this?

**Comment by mcanevet** [comment]
@cdenneen `Exec['new-alias']` can depend on `Service['postfix']`no matter where it is defined. There is no need to move it to the same class.

**Comment by cdenneen** [comment]
I originally didn’t move and it caused a circular dependency. Can you
confirm?

**Comment by mcanevet** [comment]
Oh yes, you're right. As `Class[postfix::service]` depends on `Class[postfix::files]` you can't have resource on `Class[postfix::files]` that depends on resources in `Class[postfix::service]`.

**Comment by cdenneen** [comment]
Yeah... and since `Exec['newalias']` isn't a "*file*" I didn't see issue moving it

**Comment by cdenneen** [comment]
@mcanevet @raphink Any luck in merging this and also fixing the travis issues everyone seems to be having... seems like the last merged commit had them too so not sure how valid they are.

**Comment by raphink** [comment]
@cdenneen sorry for the long delay. Could you fix the linting warning please?

    manifests/service.pp - WARNING: missing trailing comma after last element on line 19

**Comment by cdenneen** [comment]
@raphink done

**Comment by cdenneen** [comment]
@raphink looks like something is wrong with your Debian 6 and 7 tests... all others are passing.

**Comment by SiteDesignUSA** [comment]
Not trying to hijack but I cannot seem to change the inet_protocols value to ipv4 and since this is about the only result in google for my search queries, I thought I'd ask. I've read the docs. I've tried to search through the code but this module has stuff everywhere.

What I've tried to do:

`  postfix::config { 'inet_protocols':
    ensure    => true,
    value   => 'ipv4',
  }`

Maybe someone can help. I just get "Duplicate Declaration" errors.

Thank you ahead of time for your patience. I know this is out of place.

**Pull request merged**
