### PR TITLE
Update master.cf.common.erb

### PR DESCRIPTION
**Pull request by farlerac**
smtpd_bind_address -> smtp_bind_address

### CODE REVIEW

**Comment by farlerac** [comment]
smtpd_bind_address is likely a typo, should be smtp_bind_address

**Comment by raphink** [comment]
Is this a change in new versions of Postfix, or a bug in the module?

**Comment by farlerac** [comment]
IMO this is a bug in the module.  There is no option named `smtpd_bind_address` for Postfix, so I believe it is a typo.  The correct option is `smtp_bind_address`.

**Comment by raphink** [comment]
So this has been broken for over 10 years without anybody noticing. I wonder if fixing this will change the default behavior.

**Comment by farlerac** [comment]
This only comes up in the master.cf if `use_amavisd == true` so perhaps there's not many people using it.

**Comment by raphink** [comment]
Right. I'll merge.

**Pull request merged**
